packages:
  - apps/*
  - packages/*
catalog:
  hono: ^4.8.2
  "@trpc/server": ^11.5.0
  better-auth: ^1.3.28
  dotenv: ^17.2.2
  zod: ^4.1.11
  typescript: ^5.8.2
  "@types/node": ^22.13.11
  "@trpc/client": ^11.5.0
  "@prisma/client": ^7.0.0
